const DATA_KEY="tindahan_v2_data", SESSION_KEY="tindahan_v2_session";
const fresh=()=>({business:{name:"My Tindahan",owner:"Store Owner",phone:"",trialStart:new Date().toISOString(),plan:"trial",currency:"PHP"},
products:[],sales:[],expenses:[],customers:[],payments:[],users:[]});
let db=load(), session=JSON.parse(localStorage.getItem(SESSION_KEY)||"null");
function load(){try{return JSON.parse(localStorage.getItem(DATA_KEY))||fresh()}catch{return fresh()}}
function save(){localStorage.setItem(DATA_KEY,JSON.stringify(db))}
function money(n){return new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(n)||0)}
function uid(p="id"){return p+"_"+Math.random().toString(36).slice(2,10)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function daysLeft(){return Math.max(0,14-Math.floor((Date.now()-new Date(db.business.trialStart).getTime())/86400000))}
function trialActive(){return db.business.plan==="paid"||daysLeft()>0}
function salesTotal(){return db.sales.reduce((a,s)=>a+s.total,0)}
function costTotal(){return db.sales.reduce((a,s)=>a+s.cost,0)}
function expenseTotal(){return db.expenses.reduce((a,e)=>a+e.amount,0)}
function profit(){return salesTotal()-costTotal()-expenseTotal()}
function todaySales(){let d=new Date().toISOString().slice(0,10);return db.sales.filter(s=>s.date.slice(0,10)===d).reduce((a,s)=>a+s.total,0)}
function utang(){return db.customers.reduce((a,c)=>a+(Number(c.balance)||0),0)}
function toast(m){let e=document.createElement("div");e.className="toast";e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),2300)}
function closeModal(){document.getElementById("modal")?.remove()}
function modal(title,html){document.body.insertAdjacentHTML("beforeend",`<div class="modal-bg" id="modal"><div class="modal"><div class="row"><h3>${title}</h3><button class="btn ghost" onclick="closeModal()">✕</button></div>${html}</div></div>`)}
function nav(active){return `<div class="bottomnav"><div class="navinner">${[
["dashboard","🏠","Home"],["sales","🛒","Sales"],["inventory","📦","Stock"],["customers","👥","Utang"],["more","☰","More"]].map(x=>`<button class="navbtn ${active===x[0]?"active":""}" onclick="route('${x[0]}')"><span class="navicon">${x[1]}</span>${x[2]}</button>`).join("")}</div></div>`}
function shell(title,body,active="dashboard"){document.getElementById("app").innerHTML=`<div class="app"><header class="topbar"><div><div class="brand">TINDAHAN</div><div class="sub">${esc(db.business.name)}</div></div><button class="btn secondary small" onclick="route('settings')">⚙️</button></header><main class="content"><h1 class="page-title">${title}</h1>${body}</main>${nav(active)}</div>`}
function dashboard(){
let low=db.products.filter(p=>p.stock<=p.reorder);
shell("Dashboard",`<div class="trial"><b>${db.business.plan==="paid"?"Premium":"Free trial"}</b> · ${daysLeft()} day${daysLeft()===1?"":"s"} remaining ${db.business.plan==="paid"?"":"· 14-day trial"}</div>
<div class="grid stats section"><div class="card"><div class="stat-label">Today's Sales</div><div class="stat-value money">${money(todaySales())}</div></div><div class="card"><div class="stat-label">Total Sales</div><div class="stat-value money">${money(salesTotal())}</div></div><div class="card"><div class="stat-label">Net Profit</div><div class="stat-value money profit">${money(profit())}</div></div><div class="card"><div class="stat-label">Utang</div><div class="stat-value money danger-text">${money(utang())}</div></div></div>
<div class="grid two section"><button class="bigaction" onclick="newSale()">🛒<b>New Sale</b><span>Record customer purchase</span></button><button class="bigaction" onclick="newProduct()">📦<b>Add Product</b><span>Update your inventory</span></button></div>
<div class="card section"><div class="row"><h3>Low Stock</h3><button class="btn ghost small" onclick="route('inventory')">View all</button></div>${low.length?`<div class="list">${low.map(p=>`<div class="row item"><span><b>${esc(p.name)}</b><small>${esc(p.category||"Uncategorized")}</small></span><span class="badge warn">${p.stock} left</span></div>`).join("")}</div>`:`<div class="empty">No low-stock products 🎉</div>`}</div>
<div class="card section"><div class="row"><h3>Quick Summary</h3><button class="btn ghost small" onclick="route('reports')">Reports</button></div><div class="grid three mini"><div><b>${db.products.length}</b><small>Products</small></div><div><b>${db.customers.length}</b><small>Customers</small></div><div><b>${db.sales.length}</b><small>Sales</small></div></div></div>`,"dashboard")}
function sales(){let rows=[...db.sales].reverse();shell("Sales",`<div class="actions section"><button class="btn primary" onclick="newSale()">＋ New Sale</button><button class="btn secondary" onclick="newExpense()">＋ Expense</button></div><div class="card section"><div class="row"><b>Sales history</b><span class="muted">${rows.length} transactions</span></div>${rows.length?`<div class="table-wrap"><table class="table"><tr><th>Date</th><th>Items</th><th>Total</th><th>Profit</th></tr>${rows.map(s=>`<tr><td>${new Date(s.date).toLocaleDateString()}</td><td>${s.items.map(i=>esc(i.name)+" ×"+i.qty).join(", ")}</td><td>${money(s.total)}</td><td class="profit">${money(s.total-s.cost)}</td></tr>`).join("")}</table></div>`:`<div class="empty">No sales yet.</div>`}</div>`,"sales")}
let saleItems=[];
function newSale(){saleItems=[];modal("New Sale",`<div class="form"><div class="field"><label>Product</label><select id="sp">${db.products.filter(p=>p.stock>0).map(p=>`<option value="${p.id}">${esc(p.name)} — ${money(p.price)} (${p.stock})</option>`).join("")}</select></div><div class="field"><label>Quantity</label><input id="sq" type="number" min="1" value="1"></div><button class="btn secondary" onclick="addSaleItem()">Add item</button><div id="saleItems"></div><div class="row"><b>Total</b><b id="saleTotal">${money(0)}</b></div><div class="field"><label>Customer (optional)</label><select id="sc"><option value="">Cash sale</option>${db.customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}</select></div><button class="btn primary" onclick="finishSale()">Complete Sale</button></div>`);renderSaleItems()}
function addSaleItem(){let p=db.products.find(x=>x.id===document.getElementById("sp").value),q=Number(document.getElementById("sq").value);if(!p||q<1||q>p.stock)return toast("Check product and quantity.");let f=saleItems.find(i=>i.id===p.id);if(f){if(f.qty+q>p.stock)return toast("Not enough stock.");f.qty+=q}else saleItems.push({id:p.id,name:p.name,price:p.price,cost:p.cost,qty:q});renderSaleItems()}
function renderSaleItems(){let e=document.getElementById("saleItems");if(!e)return;e.innerHTML=saleItems.length?saleItems.map(i=>`<div class="row item"><span>${esc(i.name)} × ${i.qty}</span><b>${money(i.price*i.qty)}</b></div>`).join(""):`<div class="empty">Add items above.</div>`;document.getElementById("saleTotal").textContent=money(saleItems.reduce((a,i)=>a+i.price*i.qty,0))}
function finishSale(){if(!trialActive())return closeModal(),subscription();if(!saleItems.length)return toast("Add an item.");let customer=document.getElementById("sc").value;let total=saleItems.reduce((a,i)=>a+i.price*i.qty,0),cost=saleItems.reduce((a,i)=>a+i.cost*i.qty,0);saleItems.forEach(i=>db.products.find(p=>p.id===i.id).stock-=i.qty);db.sales.push({id:uid("s"),date:new Date().toISOString(),items:saleItems,total,cost,customerId:customer,payment:customer?"utang":"cash"});if(customer){let c=db.customers.find(x=>x.id===customer);c.balance=(c.balance||0)+total}save();saleItems=[];closeModal();toast(customer?"Sale added to utang.":"Sale completed.");sales()}
function inventory(){shell("Inventory",`<div class="actions section"><button class="btn primary" onclick="newProduct()">＋ Product</button><button class="btn secondary" onclick="stockAdjustment()">↕ Stock</button></div><div class="card section"><div class="table-wrap"><table class="table"><tr><th>Product</th><th>Price</th><th>Stock</th><th></th></tr>${db.products.map(p=>`<tr><td><b>${esc(p.name)}</b><br><span class="muted">${esc(p.category||"")}</span></td><td>${money(p.price)}</td><td><span class="badge ${p.stock<=p.reorder?"warn":"ok"}">${p.stock}</span></td><td><button class="btn secondary small" onclick="editProduct('${p.id}')">Edit</button></td></tr>`).join("")}</table></div></div>`,"inventory")}
function newProduct(p){p=p||{name:"",category:"",cost:"",price:"",stock:"",reorder:5};modal(p.id?"Edit Product":"Add Product",`<div class="form"><div class="field"><label>Product name</label><input id="pn" value="${esc(p.name)}"></div><div class="field"><label>Category</label><input id="pc" value="${esc(p.category)}"></div><div class="grid two"><div class="field"><label>Cost</label><input id="pco" type="number" step=".01" value="${p.cost}"></div><div class="field"><label>Selling price</label><input id="pp" type="number" step=".01" value="${p.price}"></div></div><div class="grid two"><div class="field"><label>Stock</label><input id="ps" type="number" value="${p.stock}"></div><div class="field"><label>Low-stock level</label><input id="pr" type="number" value="${p.reorder}"></div></div><button class="btn primary" onclick="saveProduct('${p.id||""}')">Save Product</button></div>`)}
function saveProduct(pid){let name=document.getElementById("pn").value.trim();if(!name)return toast("Product name required.");let d={name,category:document.getElementById("pc").value.trim(),cost:+document.getElementById("pco").value||0,price:+document.getElementById("pp").value||0,stock:+document.getElementById("ps").value||0,reorder:+document.getElementById("pr").value||0};if(pid)Object.assign(db.products.find(p=>p.id===pid),d);else db.products.push({id:uid("p"),...d});save();closeModal();inventory();toast("Product saved.")}
function editProduct(id){newProduct(db.products.find(p=>p.id===id))}
function stockAdjustment(){modal("Stock Adjustment",`<div class="form"><div class="field"><label>Product</label><select id="ap">${db.products.map(p=>`<option value="${p.id}">${esc(p.name)} (${p.stock})</option>`).join("")}</select></div><div class="field"><label>Change (+ add / - remove)</label><input id="aq" type="number" value="1"></div><button class="btn primary" onclick="applyAdjustment()">Update</button></div>`)}
function applyAdjustment(){let p=db.products.find(x=>x.id===document.getElementById("ap").value),q=+document.getElementById("aq").value;if(!p||p.stock+q<0)return toast("Invalid stock.");p.stock+=q;save();closeModal();inventory();toast("Stock updated.")}
function customers(){shell("Customers & Utang",`<div class="actions section"><button class="btn primary" onclick="newCustomer()">＋ Customer</button></div><div class="card section">${db.customers.length?`<div class="table-wrap"><table class="table"><tr><th>Customer</th><th>Phone</th><th>Utang</th><th></th></tr>${db.customers.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.phone||"—")}</td><td class="${c.balance>0?"danger-text":""}">${money(c.balance||0)}</td><td>${c.balance>0?`<button class="btn secondary small" onclick="payment('${c.id}')">Pay</button>`:"<span class='badge ok'>Clear</span>"}</td></tr>`).join("")}</table></div>`:`<div class="empty">No customers yet.</div>`}</div>`,"customers")}
function newCustomer(){modal("Add Customer",`<div class="form"><div class="field"><label>Name</label><input id="cn"></div><div class="field"><label>Phone</label><input id="cp"></div><button class="btn primary" onclick="saveCustomer()">Save Customer</button></div>`)}
function saveCustomer(){let n=document.getElementById("cn").value.trim();if(!n)return toast("Name required.");db.customers.push({id:uid("c"),name:n,phone:document.getElementById("cp").value.trim(),balance:0});save();closeModal();customers()}
function payment(id){let c=db.customers.find(x=>x.id===id);modal("Customer Payment",`<div class="form"><p><b>${esc(c.name)}</b> owes ${money(c.balance)}.</p><div class="field"><label>Amount</label><input id="pay" type="number" max="${c.balance}" value="${c.balance}"></div><button class="btn primary" onclick="applyPayment('${id}')">Record Payment</button></div>`)}
function applyPayment(id){let c=db.customers.find(x=>x.id===id),v=+document.getElementById("pay").value;if(v<0||v>c.balance)return toast("Invalid payment.");c.balance-=v;db.payments.push({id:uid("pay"),customerId:id,amount:v,date:new Date().toISOString()});save();closeModal();customers();toast("Payment recorded.")}
function newExpense(){modal("Add Expense",`<div class="form"><div class="field"><label>Description</label><input id="ed"></div><div class="field"><label>Amount</label><input id="ea" type="number" step=".01"></div><button class="btn primary" onclick="saveExpense()">Save Expense</button></div>`)}
function saveExpense(){let d=document.getElementById("ed").value.trim(),a=+document.getElementById("ea").value;if(!d||a<=0)return toast("Enter description and amount.");db.expenses.push({id:uid("e"),description:d,amount:a,date:new Date().toISOString()});save();closeModal();sales();toast("Expense saved.")}
function reports(){shell("Reports",`<div class="grid stats section"><div class="card"><div class="stat-label">Sales</div><div class="stat-value money">${money(salesTotal())}</div></div><div class="card"><div class="stat-label">Product Cost</div><div class="stat-value money">${money(costTotal())}</div></div><div class="card"><div class="stat-label">Expenses</div><div class="stat-value money">${money(expenseTotal())}</div></div><div class="card"><div class="stat-label">Net Profit</div><div class="stat-value money profit">${money(profit())}</div></div></div><div class="card section"><h3>Business health</h3><p class="muted">Profit = sales − product cost − expenses. Use this as a simple operating report; it is not formal accounting.</p></div>`,"more")}
function more(){shell("More",`<div class="grid two section"><button class="bigaction" onclick="route('reports')">📊<b>Reports</b><span>Sales and profit</span></button><button class="bigaction" onclick="route('settings')">⚙️<b>Settings</b><span>Store profile and data</span></button><button class="bigaction" onclick="backup()">💾<b>Backup</b><span>Download your data</span></button><button class="bigaction" onclick="subscription()">💳<b>Subscription</b><span>Trial and payment</span></button></div>`,"more")}
function settings(){shell("Settings",`<div class="card section"><h3>Store profile</h3><div class="form"><div class="field"><label>Store name</label><input id="bn" value="${esc(db.business.name)}"></div><div class="field"><label>Owner name</label><input id="bo" value="${esc(db.business.owner)}"></div><div class="field"><label>Phone</label><input id="bp" value="${esc(db.business.phone||"")}"></div><button class="btn primary" onclick="saveSettings()">Save</button></div></div><div class="card section"><h3>Subscription</h3><p class="muted">${db.business.plan==="paid"?"Your account is marked Paid in this prototype.":"You are on the 14-day free trial."}</p><button class="btn secondary" onclick="subscription()">View subscription</button></div><div class="card section"><h3>Backup</h3><p class="muted">Export your current local data regularly while this version is local-only.</p><button class="btn secondary" onclick="backup()">Export backup</button><button class="btn danger" onclick="resetData()">Reset demo data</button></div>`)}
function saveSettings(){db.business.name=document.getElementById("bn").value.trim()||"My Tindahan";db.business.owner=document.getElementById("bo").value.trim()||"Store Owner";db.business.phone=document.getElementById("bp").value.trim();save();toast("Saved.");settings()}
function backup(){let b=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="tindahan-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(a.href)}
function subscription(){modal("TINDAHAN Subscription",`<div class="card"><h3>${db.business.plan==="paid"?"Paid Plan":"14-Day Free Trial"}</h3><p>${daysLeft()} day(s) remaining.</p><p class="muted">Production billing is not connected in this offline build. Before launch, we will replace this screen with a secure subscription/payment flow and server-side account status.</p><div class="trial">Suggested future flow: choose plan → pay → payment verified → account continues.</div></div><button class="btn ghost" onclick="closeModal()">Close</button>`)}
function resetData(){if(confirm("Reset all local TINDAHAN data?")){db=fresh();save();route("dashboard")}}
function route(p){if(!trialActive()&&p!=="more"&&p!=="settings"&&p!=="dashboard")return subscription();({dashboard,sales,inventory,customers,reports,settings,more}[p]||dashboard)()}
function start(){route("dashboard")}
start();
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});